Doing some debugging to reduce to python files only

diff --git a/.github/workflows/format.yml b/.github/workflows/format.yml
--- a/.github/workflows/format.yml
+++ b/.github/workflows/format.yml
@@ -25,13 +25,15 @@ jobs:
       shell: bash
       run: |
         pip install black
-        success=1
+        failed_formatting=1
         echo "Checking files ${{ inputs.files }}"
         for file in ${{ inputs.files }}
         do
           echo "Checking $file"
-          black --check $file || success=0
+          black --check $file || failed_formatting=$((failed_formatting + 1))
         done
-        if [ $success -eq 0 ]; then
+        if [ $failed_formatting -ne 0 ]; then
+          echo "Formatting failed for $failed_formatting files"
           exit 1
         fi
+        exit 0
diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -25,13 +25,15 @@ jobs:
       shell: bash
       run: |
         pip install flake8 flake8-pyproject
-        success=1
+        failed_linting=0
         echo "Linting files ${{ inputs.files }}"
         for file in ${{ inputs.files }}
         do
           echo "Linting $file"
-          flake8 $file || success=0
+          flake8 $file || failed_linting=$((failed_linting + 1))
         done
-        if [ $success -eq 0 ]; then
+        if [ $success -ne 0 ]; then
+          echo "Linting failed on $failed_linting files"
           exit 1
         fi
+        exit 1
