Lint job change

diff --git a/.github/workflows/JOB_lint.yml b/.github/workflows/JOB_lint.yml
--- a/.github/workflows/JOB_lint.yml
+++ b/.github/workflows/JOB_lint.yml
@@ -26,14 +26,26 @@ jobs:
       run: |
         pip install flake8 flake8-pyproject
         failed_linting=0
+        failed_files=""
         echo "Linting files ${{ inputs.files }}"
+        MARKDOWN_OUTPUT=""
         for file in ${{ inputs.files }}
         do
           echo "Linting $file"
-          flake8 $file || failed_linting=$((failed_linting + 1))
+          flake8 $file || failed_linting=$((failed_linting + 1) && failed_files="$failed_files $file")
         done
-        if [ $success -ne 0 ]; then
+        if [ $failed_linting -ne 0 ]; then
           echo "Linting failed on $failed_linting files"
+          echo "Failed files: $failed_files"
+
+          echo "# Linting failed 😢" >> $GITHUB_STEP_SUMMARY
+          echo "## Failed files" >> $GITHUB_STEP_SUMMARY
+          for file in $failed_files ; do
+            echo "- $file" >> $GITHUB_STEP_SUMMARY
+          done
           exit 1
+        else
+          echo "# Linting passed 🎉" >> $GITHUB_STEP_SUMMARY
+          echo "Tested files: ${{ inputs.files }}" >> $GITHUB_STEP_SUMMARY
         fi
         exit 1
