Restructure linting and formatting

diff --git a/.github/workflows/JOB_format.yml b/.github/workflows/JOB_format.yml
--- a/.github/workflows/JOB_format.yml
+++ b/.github/workflows/JOB_format.yml
@@ -26,14 +26,21 @@ jobs:
       run: |
         pip install black
         failed_formatting=1
-        echo "Checking files *${{ inputs.files }}*"
+        failed_files=""
+        echo "Checking files [${{ inputs.files }}]"
         for file in ${{ inputs.files }}
         do
           echo "Checking $file"
-          black --check $file || failed_formatting=$((failed_formatting + 1))
+          black --check $file || failed_formatting=$((failed_formatting + 1) && failed_files="$failed_files $file")
         done
         if [ $failed_formatting -ne 0 ]; then
-          echo "Formatting failed for $failed_formatting files"
+          echo "Formatting failed for $failed_formatting files 😢"
+          echo "Failed files
+          for file in $failed_files ; do
+            echo "- $file"
+          done
           exit 1
+        else
+          echo "Formatting passed for all files 🎉"
         fi
         exit 0
